project:
  type: website

website:
  title: "grateful-package-issues"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    bibliography: 
    - ".pandoc/grateful-refs.bib"
  pdf:
    papersize: a4
    bibliography: 
    - ".pandoc/grateful-refs.bib"
  docx:
    bibliography: 
    - ".pandoc/grateful-refs.bib"
